# es.toml - v10.1.3.2
[addon]
appDesc = '''Descargar videos de la web.'''
restore_purchase_button = '''Restaurar compra'''
get_premium_button = '''Ir a premium'''
back = '''Atrás'''
rm_notifications_all = '''Descartar todas las notificaciones'''
waiting_for_media = '''Esperando medios…'''
nomedia_title = '''¿No ve el medio que está buscando?'''
nomedia_description = '''Inicie el video (y omita los anuncios, si los hay) para ayudar a detectar el medio. O informe que faltan medios.'''
nomedia_reload_button = '''Forzar detección'''
nomedia_reload_button_tooltip = '''Forzar recarga de página (borrar cookies)'''
show_nomedia_button = '''¿No hay video?'''
show_nomedia_button_tooltip = '''Haga clic aquí si no encuentra su video.'''
setting_button_tooltip = '''Ajustes'''
history_button_tooltip = '''Mostrar historial de descargas'''
show_all_history_button = '''Mostrar todo'''
complete_title = '''Completado'''
hide_complete_button = '''esconder'''
translate_button_tooltip = '''Ayudar a traducir VDH'''
open_source_tab_button_tooltip = '''Abrir pestaña de código'''
retry_download_button_tooltip = '''Reintentar descarga'''
delete_file_button_tooltip = '''Eliminar archivo'''
download_directory_button_tooltip = '''Mostrar directorio de descargas'''
clear_downloaded_tooltip = '''Limpiar descargas completadas'''
show_in_popup_button_tooltip = '''Mostrar en ventana emergente'''
show_in_sidebar_button_tooltip = '''Mostrar en la barra lateral'''
video_not_playing_button_tooltip = '''¿No se reproduce el video?'''
play = '''Reproducir'''
warn_drm_tooltip = '''Se ha detectado DRM'''
version_title = '''Versión'''
account_title = '''Cuenta'''
one_hundred_downloads_title = '''¡Has descargado 100 vídeos!'''
leave_review_description = '''Hola 🤚 Video DownloadHelper es de uso gratuito. ¿Le importaría dejar una buena reseña? Me sería de gran ayuda 😊.'''
leave_review_button = '''Dejar una reseña'''
account_status = '''Estado'''
account_status_premium = '''Premium ($1)'''
free_account = '''Plan gratuito'''
copy_to_clipboard = '''Copiar información al portapapeles'''
my_account_button = '''Mi cuenta'''
download_title = '''Descargas'''
show_notification = '''Mostrar notificación una vez completada la descarga'''
max_parallel_downloads = '''Descargas simultáneas máximas'''
saveas_detected_warning = '''Hemos detectado que tu navegador muestra un cuadro de diálogo 'Guardar como', una vez la descarga ha finalizado. Recomendamos deshabilitar esa opción en los ajustes de tu navegador'''
change_saveas_setting = '''Cambiar ajuste'''
download_directory_title = '''Carpeta de descargas'''
download_directory_description = '''Los vídeos se descargan en la carpeta de descarga por defecto de su navegador. También puede especificar una subcarpeta. Los directorios de descarga específicos del sitio web se pueden configurar con la herramienta de nombres inteligentes.'''
change_browser_download_directory = '''Cambiar la carpeta de descarga del navegador'''
bad_download_subdirectory_warning = '''La subcarpeta especificada no es válida.'''
download_subdirectory = '''Subcarpeta de descarga'''
private_browsing_title = '''Navegación privada'''
private_browsing_warning = '''Video DownloadHelper no está habilitado en la navegación privada.'''
private_browsing_notifications = '''Mostrar notificación para descargas privadas'''
private_browsing_button = '''Cambiar configuración de navegación privada'''
throttle_youtube = '''Limitar YouTube (descargas más lentas, pero con menos probabilidades de bloqueo)'''
prefer_original_audio = '''Preferir audio original'''
prefer_hls = '''Preferir HLS'''
settings_history_title = '''Historial'''
transient_history_description = '''Mostrar descargas completas en el panel'''
history_limit = '''Días antes de olvidar las descargas'''
appearance_title = '''Apariencia'''
theme_title = '''Tema'''
theme_light = '''Tema claro'''
theme_dark = '''Tema oscuro'''
theme_system = '''Tema del sistema'''
popup_size_title = '''Tamaño de la ventana'''
popup_size_small = '''Pequeño'''
popup_size_medium = '''Mediano'''
popup_size_big = '''Grande'''
panel_position_title = '''Posición del panel'''
use_popup = '''Usar ventana emergente'''
use_sidebar = '''Usar barra lateral'''
behavior_title = '''Comportamiento'''
controls_title = '''Controles'''
show_in_context_menu = '''Mostrar menú de descarga en el menú contextual de la página'''
restart_addon = '''Reiniciar complemento'''
reset_settings = '''Restablecer ajustes'''
prefered_quality = '''Calidad de vídeo preferida'''
prefered_quality_highest = '''El más alto (descarga lenta, alta resolución)'''
prefered_quality_1080p = '''1080p (bueno por defecto)'''
prefered_quality_720p = '''720p (descarga rápida, baja resolución)'''
prefer_mkv = '''Descargar como MKV cuando sea posible'''
preview_mode_title = '''Vista previa de los medios'''
preview_mode_none = '''Desactivado'''
preview_mode_video = '''Vista previa de vídeo corto'''
preview_mode_image = '''Imagen'''
history_title = '''Historial de descargas'''
history_warning = '''No registramos su historial de descargas. ¿Desea que Video DownloadHelper recuerde su historial de descargas?'''
history_warning_2 = '''No se preocupe, todo permanece en su equipo. Valoramos su privacidad.'''
enable_history = '''Habilitar historial'''
clear_history = '''Borrar historial'''
disable_history = '''Deshabilitar historial'''
no_downloads_yet = '''Aún no hay descargas.'''
download_failed = '''Descarga fallida'''
download_failed_description = '''Algo no ha funcionado. Informe del error y haremos todo lo posible por averiguar por qué ha fallado (enviamos la URL del video de forma anónima, ¡no lo rastreamos!).'''
download_interrupted = '''Descarga interrumpida'''
download_interrupted_description = '''Logramos descargar tu archivo, pero hubo problemas de red, por lo que podría ser más corto de lo esperado. Intentamos dar soporte a la mayor cantidad de sitios web posible, así que sería de gran ayuda que nos informaras de este problema (¡es anónimo!).'''
download_with_drm_failed_description = '''Algo no ha funcionado. Creemos que este video tiene DRM. No admitimos videos con DRM.'''
no_youtube = '''No se permite la descarga desde YouTube'''
no_youtube_description = '''Lamentablemente, Chrome Web Store no permite que las extensiones descarguen videos de YouTube. Otros navegadores como Firefox no tienen esta limitación.'''
no_youtube_description_2 = '''Por favor, use Firefox o Microsoft Edge'''
premium_required = '''Se requiere el estado Premium'''
premium_yt_required_description = '''Sin el estado Premium debe esperar dos horas entre descargas de videos de YouTube.'''
premium_hls_required_description = '''Sin el estado Premium, solo se puede realizar una descarga HLS dos horas después de la anterior.'''
premium_all_required_description = '''Sin estado Premium, una descarga solo se puede realizar 2 horas después de la anterior.'''
youtube_too_many_downloads = '''Ups, parece que YouTube está bloqueado'''
youtube_too_many_downloads_description = '''YouTube, a veces, limitará cuántos vídeos se pueden solicitar. Lamentablemente, no podemos hacer nada al respecto. Inténtelo de nuevo más tarde.'''
stop = '''Detener'''
cancel = '''Cancelar'''
copy_url = '''Copiar URL'''
always_copy_url = '''Copiar siempre la URL'''
download_button = '''Descargar'''
download_as_button_and_menu = '''Descargar como...'''
rename_short = '''Renombrar'''
always_download_as_menu = '''Siempre Descargar Como...'''
download_audio_button = '''Audio'''
download_audio_and_video_menu = '''Descargar audio y video'''
download_audio_only_menu = '''Descargar solo audio'''
audio_only_for_this_website = '''Siempre solo audio para este sitio web.'''
details = '''Detalles'''
report = '''Informar'''
reporting = '''Informando…'''
reported_thankyou = '''¡Gracias!'''
not_playing_title = '''¿No se reproduce el vídeo?'''
not_playing_broken_title = '''¿El audio o el video no funcionan?'''
not_playing_broken_description = '''Informe del fallo del medio. Haremos todo lo posible por averiguar por qué ha fallado (enviamos la URL del video de forma anónima, ¡no lo rastreamos!).'''
not_playing_broken_solution_title = '''Pruebe un reproductor de video moderno'''
not_playing_broken_solution_windows_1 = '''Recomendamos VLC:'''
not_playing_broken_solution_mac_1 = '''Recomendamos IINA:'''
not_playing_broken_solution_2 = '''es moderno, seguro y de Código abierto.'''
not_playing_default_player = '''Asegúrese de que su reproductor de video está configurado como reproductor predeterminado del sistema'''
not_playing_default_player_solution_windows = '''En el \“Panel de control\” de Windows, haga clic en \“Programas predeterminados\” y cambie los programas predeterminados para su reproductor.'''
not_playing_default_player_solution_mac = '''Abra el directorio de descargas y haga clic con el botón derecho del mouse en el archivo de video. Haga clic en “Obtener información”. En la sección “Abrir con”, seleccione IINA. Haga clic en el botón “Cambiar todo”.'''

[web]
back = '''Atrás'''
header_help = '''Ayuda'''
header_community = '''Comunidad'''
activate_title = '''Activación'''
activate_pending = '''Pendiente…'''
activate_success = '''Éxito'''
activate_error = '''Error'''
activate_no_addon_found = '''No se ha encontrado ningún complemento. ¿Está instalado el complemento?'''
activate_no_method_found = '''No se ha encontrado ningún método.'''
activate_help_me = '''Ayuda'''
issue_title = '''Restaurar compra'''
issue_submit = '''Enviar'''
issue_thank_you = '''Gracias'''
issue_enter_email = '''Para restaurar su compra, introduzca la dirección de correo electrónico que utilizó para comprar su licencia:'''
issue_email_sent = '''Le acabamos de enviar un correo electrónico con un enlace que activará su producto.'''
issue_or_digit = '''O bien, también puede introducir el código de 6 dígitos que le hemos enviado:'''
issue_just_digit = '''Introduzca el código de 6 dígitos que le enviamos:'''
issue_i_have_a_code = '''(Haga click aquí si ya tiene un código)'''
issue_i_have_a_key = '''(Haga click aquí si tiene una clave de licencia)'''
issue_key = '''Introduzca su clave de licencia de Video DownloadHelper:'''
landing_text1 = '''Descargue cualquier video de cualquier sitio web, ¡funciona!'''
landing_text2 = '''Más de 1000 sitios web compatibles'''
landing_text3 = '''Con la confianza de 7 millones de usuarios'''
landing_text4 = '''4.5 estrellas en la tienda de extensiones'''
landing_install_for_google = '''Instalar para Chrome'''
landing_install_for_mozilla = '''Instalar para Firefox'''
landing_install_for_microsoft = '''Instalar para Edge'''
landing_feature1_title = '''Descarga HD a toda velocidad'''
landing_feature1_description = '''Descargue videos en alta definición a la máxima velocidad. Nos enorgullece afirmar que contamos con el motor de descarga más rápido del mercado.'''
landing_feature2_title = '''Archivar videos'''
landing_feature2_description = '''Archive sus videos favoritos y asegúrese de que no se pierda nada.'''
landing_feature3_title = '''Compatibilidad con transmisiones en directo'''
landing_feature3_description = '''Disfrute de la visualización sin conexión de transmisiones en directo, sin limitaciones de tiempo real.'''
landing_feature4_title = '''Descarga de audio'''
landing_feature4_description = '''Extraiga el audio de los videos y conviértalo a MP3 o podcasts para escucharlo fácilmente.'''
premium_hero1 = '''Pague una vez y úselo para siempre'''
premium_hero2 = '''Obtenga una licencia de por vida para Video DownloadHelper'''
premium_hero3 = '''Descargue todos los videos que quiera, sin límites.'''
welcome_text = '''¡Ahora no te perderás ningún vídeo!'''
welcome_pin_message = '''Fije el icono del complemento a su barra de herramientas:'''
